<Project Sdk="Microsoft.NET.Sdk">

  <!--
  Imports silksong path properties only if present in order to allow CI builds. The file should be gitignored.
  If you are checking out from git and need to create a new one, you can use `dotnet new silksongpath` to generate one.
  -->
  <Import Condition="Exists('SilksongPath.props')" Project="SilksongPath.props" />

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RestoreAdditionalProjectSources>
        https://nuget.bepinex.dev/v3/index.json
    </RestoreAdditionalProjectSources>
      <!--Allow access of private members at runtime.-->
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ModName>KnightInSilkSong</ModName>
    <NeutralLanguage>ZH</NeutralLanguage>
  </PropertyGroup>

  <PropertyGroup>
    <!--These properties will control the generated plugin info. Version is also used by various parts of the build system.-->
    <AssemblyTitle>KnightInSilkSong</AssemblyTitle>
    <Version>0.6.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.0.8" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="Hamunii.BepInEx.AutoPlugin" Version="2.0.1" PrivateAssets="all" />
    <!--If you're unable resolve this dependency, check that you're using the nuget v3 package feed instead of v2.-->
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" PrivateAssets="all" />
    <!-- <PackageReference Include="UnityEngine.Modules" Version="6000.0.50" IncludeAssets="compile" /> -->
    <PackageReference Include="Silksong.PrepatcherPlugin" Version="1.3.0" PrivateAssets="all"/>

    <LocalReferences Include="$(ManagedDir)*.dll" Exclude="$(ManagedDir)Mono*.dll;$(ManagedDir)netstandard.dll;$(ManagedDir)System*.dll;$(ManagedDir)mscorlib.dll" />
    <LocalReferences Include="$(DebugMod)"/>
    <Reference Include="@(LocalReferences)" Private="false" Publicize="true" />
    <EmbeddedResource Include="Resources/*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Knight/Knight.csproj" Publicize="true"/>
  </ItemGroup>
  <ItemGroup>
      <Binaries Include="$(TargetPath)" LocalDir="/" PackDir="plugins" />
      <Binaries Include="$(TargetDir)/$(TargetName).pdb" LocalDir="/" PackDir="plugins" />
      <I18N Include="languages/*.json" LocalDir="/languages/" PackDir="plugins/languages" />

      </ItemGroup>

  <Target Name="CopyMod" AfterTargets="PostBuildEvent" Condition="'$(SilksongFolder)' != ''">


      <Copy SourceFiles="@(Binaries)" DestinationFolder="$(SilksongFolder)/BepInEx/plugins/$(ModName)" />
      <Copy SourceFiles="@(I18N)" DestinationFolder="$(SilksongFolder)/BepInEx/plugins/$(ModName)/languages" />
      <Copy SourceFiles="../README.md" DestinationFolder="$(SilksongFolder)/BepInEx/plugins/$(ModName)" />
  </Target>
  <Target Name="BuildPushishPack" AfterTargets="CopyMod" Condition="'$(PublishFolder)' != ''">
      <ItemGroup>
          <Package Include="../README.md" />
          <Package Include="../CHANGELOG.md" />
          <Package Include="../manifest.json" />
      </ItemGroup>

      <Copy SourceFiles="@(Binaries)" DestinationFolder="$(PublishFolder)/$(ModName)/ThunderStore" />
      <Copy SourceFiles="@(Binaries)" DestinationFolder="$(PublishFolder)/$(ModName)/GitHub" />
      <Copy SourceFiles="@(Package)" DestinationFolder="$(PublishFolder)/$(ModName)/ThunderStore" />
      <Copy SourceFiles="../README.md" DestinationFolder="$(PublishFolder)/$(ModName)/GitHub" />
      <Copy SourceFiles="../CHANGELOG.md" DestinationFolder="$(PublishFolder)/$(ModName)/GitHub" />
      <ZipDirectory SourceDirectory="$(PublishFolder)/$(ModName)/ThunderStore" DestinationFile="$(PublishFolder)/$(ModName)/$(ModName)$(Version)_for_thunderstore.zip" Overwrite="True" />
      <ZipDirectory SourceDirectory="$(PublishFolder)/$(ModName)/GitHub" DestinationFile="$(PublishFolder)/$(ModName)/$(ModName)$(Version).zip" Overwrite="True" />
      </Target>
</Project>
